# Hostname (and path) to the root
baseURL = "https://miladnazari.be/"
# Default pagination every X items
Paginate = 10
# Enable this to make all relative URLs relative to content
# root. Note that this does not affect absolute URLs.
relativeURLs = true
# Missing translations will default to this content language
DefaultContentLanguage = "en"
# Do not inject generator meta tag on homepage
disableHugoGeneratorInject = true
# Disable RSS feed
disableKinds = ["RSS"]
[params]
    description = "Personal website and blog"
[languages]
    [languages.en]
        baseURL = "https://miladnazari.be/"
        title = "Milad Nazari"
        weight = 1
        [[languages.en.menu.main]]
        identifier = "Cv"
        url    = "/"
        name   = "CV"
        weight = 1
        
        [[languages.en.menu.main]]
        identifier = "projects"
        url    = "/projects/"
        name   = "Projects"
        weight = 1
        
    [languages.nl]
        baseURL = "https://nl.miladnazari.be/"
        title = "Milad Nazari"
        weight = 2
        [languages.nl.params]
            description = "Persoonlijke website en blog"
            currentWork = "Assistent lesgever @CodeFever"
        [[languages.nl.menu.main]]
        identifier = "Cv"
        url    = "/"
        name   = "CV"
        weight = 2
        [[languages.nl.menu.main]]
        identifier = "projecten"
        url    = "/projecten/"
        name   = "Projecten"
        weight = 2

